var ArrVeh = '{"Specs":[' +  
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Tipo","feature":"Tipo","Orden":"0","Url":"Motor_Tipo","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Tipo","feature":"Tipo","Orden":"1","Url":"","Mazda6GTLX":" SKYACTIV-G 2,5L / 16 válvulas / Dual S-VT / Inyección directa","MazdaCX5PrimeMT":" SKYACTIV-G 2,0 L / 16 válvulas / Dual S-VT / Inyección Directa","MazdaCX5PrimeAT":" SKYACTIV-G 2,0 L / 16 válvulas / Dual S-VT / Inyección Directa","MazdaCX5Touring4x2":" SKYACTIV-G 2,0 L / 16 válvulas / Dual S-VT / Inyección Directa","MazdaCX5TouringAWD":" SKYACTIV-G 2,0 L / 16 válvulas / Dual S-VT / Inyección Directa","MazdaCX5GranTouring":" SKYACTIV-G 2,5 L / 16 válvulas / Dual S-VT / Inyección Directa","MazdaCX5GrandTouringLX":" SKYACTIV-G 2,5 L / 16 válvulas / Dual S-VT / Inyección Directa"},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Cilindraje (c.c.)","feature":"Cilindraje (c.c.)","Orden":"0","Url":"Motor_Cilindraje","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Cilindraje (c.c.)","feature":"Cilindraje (c.c.)","Orden":"1","Url":"","Mazda6GTLX":"2.488","MazdaCX5PrimeMT":"1.998","MazdaCX5PrimeAT":"1.998","MazdaCX5Touring4x2":"1.998","MazdaCX5TouringAWD":"1.998","MazdaCX5GranTouring":"2.488","MazdaCX5GrandTouringLX":"2.488"},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Número de cilindros","feature":"Número de cilindros","Orden":"0","Url":"Motor_Cilindros","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Número de cilindros","feature":"Número de cilindros","Orden":"1","Url":"","Mazda6GTLX":"4","MazdaCX5PrimeMT":"4","MazdaCX5PrimeAT":"4","MazdaCX5Touring4x2":"4","MazdaCX5TouringAWD":"4","MazdaCX5GranTouring":"4","MazdaCX5GrandTouringLX":"4"},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Relación de compresión","feature":"Relación de compresión","Orden":"0","Url":"Motor_Compresion","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Relación de compresión","feature":"Relación de compresión","Orden":"1","Url":"","Mazda6GTLX":"13,0:1","MazdaCX5PrimeMT":"13,0:1","MazdaCX5PrimeAT":"13,0:1","MazdaCX5Touring4x2":"13,0:1","MazdaCX5TouringAWD":"13,0:1","MazdaCX5GranTouring":"13,0:1","MazdaCX5GrandTouringLX":"13,0:1"},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Potencia máxima (hp/r.p.m.)","feature":"Potencia máxima (hp/r.p.m.)","Orden":"0","Url":"Motor_Potencia","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Potencia máxima (hp/r.p.m.)","feature":"Potencia máxima (hp/r.p.m.)","Orden":"1","Url":"","Mazda6GTLX":"\'185/5.700","MazdaCX5PrimeMT":"153  / 6.000","MazdaCX5PrimeAT":"153  / 6.000","MazdaCX5Touring4x2":"153  / 6.000","MazdaCX5TouringAWD":"152 / 6.000","MazdaCX5GranTouring":"185 / 5.700","MazdaCX5GrandTouringLX":"185 / 5.700"},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Torque máximo (kg-m/r.p.m.)","feature":"Torque máximo (kg-m/r.p.m.)","Orden":"0","Url":"Motor_Torque","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Torque máximo (kg-m/r.p.m.)","feature":"Torque máximo (kg-m/r.p.m.)","Orden":"1","Url":"","Mazda6GTLX":"\'25,49/3.250","MazdaCX5PrimeMT":"20,39 / 4.000","MazdaCX5PrimeAT":"20,39 / 4.000","MazdaCX5Touring4x2":"20,39 / 4.000","MazdaCX5TouringAWD":"20,19 / 4.000","MazdaCX5GranTouring":"25,49 / 4.000","MazdaCX5GrandTouringLX":"25,49 / 4.000"},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Tipo de combustible","feature":"Tipo de combustible","Orden":"0","Url":"Motor_combustible","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Tipo de combustible","feature":"Tipo de combustible","Orden":"1","Url":"","Mazda6GTLX":"Gasolina corriente","MazdaCX5PrimeMT":"Gasolina corriente","MazdaCX5PrimeAT":"Gasolina corriente","MazdaCX5Touring4x2":"Gasolina corriente","MazdaCX5TouringAWD":"Gasolina corriente","MazdaCX5GranTouring":"Gasolina corriente","MazdaCX5GrandTouringLX":"Gasolina corriente"},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Tanque de combustible (L)","feature":"Tanque de combustible (L)","Orden":"0","Url":"Motor_Tanque","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-G : Motor","SubGroup":"Tanque de combustible (L)","feature":"Tanque de combustible (L)","Orden":"1","Url":"","Mazda6GTLX":"62","MazdaCX5PrimeMT":"56","MazdaCX5PrimeAT":"56","MazdaCX5Touring4x2":"56","MazdaCX5TouringAWD":"58","MazdaCX5GranTouring":"58","MazdaCX5GrandTouringLX":"58"},' + 
'{"Group":"SKYACTIV-DRIVE : Transmisión","SubGroup":"Tipo","feature":"Tipo","Orden":"0","Url":"Drive_tipo","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-DRIVE : Transmisión","SubGroup":"Tipo","feature":"Tipo","Orden":"1","Url":"","Mazda6GTLX":"SKYACTIV-DRIVE, Automática 6 Vel., Activematic (con modo manual)","MazdaCX5PrimeMT":"SKYACTIV-MT 6 vel.","MazdaCX5PrimeAT":"SKYACTIV-DRIVE, AT 6 vel. Activematic","MazdaCX5Touring4x2":"SKYACTIV-DRIVE, AT 6 vel. Activematic","MazdaCX5TouringAWD":"SKYACTIV-DRIVE, AT 6 vel. Activematic","MazdaCX5GranTouring":"SKYACTIV-DRIVE, AT 6 vel. Activematic","MazdaCX5GrandTouringLX":"SKYACTIV-DRIVE, AT 6 vel. Activematic"},' + 
'{"Group":"SKYACTIV-DRIVE : Transmisión","SubGroup":"Tracción","feature":"Tracción","Orden":"0","Url":"Dive_Traccion","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-DRIVE : Transmisión","SubGroup":"Tracción","feature":"Tracción","Orden":"1","Url":"","Mazda6GTLX":"-","MazdaCX5PrimeMT":"4x2 delantera","MazdaCX5PrimeAT":"4x2 delantera","MazdaCX5Touring4x2":"4x2 delantera","MazdaCX5TouringAWD":"Sistema inteligente AWD","MazdaCX5GranTouring":"Sistema inteligente AWD","MazdaCX5GrandTouringLX":"Sistema inteligente AWD"},' + 
'{"Group":"Relaciones de caja","SubGroup":"1ª","feature":"1ª","Orden":"0","Url":"Relaciones_1","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Relaciones de caja","SubGroup":"1ª","feature":"1ª","Orden":"1","Url":"","Mazda6GTLX":"3,552","MazdaCX5PrimeMT":"3,700","MazdaCX5PrimeAT":"3,552","MazdaCX5Touring4x2":"3,552","MazdaCX5TouringAWD":"3,552","MazdaCX5GranTouring":"3,552","MazdaCX5GrandTouringLX":"3,552"},' + 
'{"Group":"Relaciones de caja","SubGroup":"2ª","feature":"2ª","Orden":"0","Url":"Relaciones_2","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Relaciones de caja","SubGroup":"2ª","feature":"2ª","Orden":"1","Url":"","Mazda6GTLX":"2,022","MazdaCX5PrimeMT":"1,947","MazdaCX5PrimeAT":"2,022","MazdaCX5Touring4x2":"2,022","MazdaCX5TouringAWD":"2,022","MazdaCX5GranTouring":"2,022","MazdaCX5GrandTouringLX":"2,022"},' + 
'{"Group":"Relaciones de caja","SubGroup":"3ª","feature":"3ª","Orden":"0","Url":"Relaciones_3","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Relaciones de caja","SubGroup":"3ª","feature":"3ª","Orden":"1","Url":"","Mazda6GTLX":"1,452","MazdaCX5PrimeMT":"1,300","MazdaCX5PrimeAT":"1,452","MazdaCX5Touring4x2":"1,452","MazdaCX5TouringAWD":"1,452","MazdaCX5GranTouring":"1,452","MazdaCX5GrandTouringLX":"1,452"},' + 
'{"Group":"Relaciones de caja","SubGroup":"4ª","feature":"4ª","Orden":"0","Url":"Relaciones_4","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Relaciones de caja","SubGroup":"4ª","feature":"4ª","Orden":"1","Url":"","Mazda6GTLX":"1,000","MazdaCX5PrimeMT":"1,029","MazdaCX5PrimeAT":"1,000","MazdaCX5Touring4x2":"1,000","MazdaCX5TouringAWD":"1,000","MazdaCX5GranTouring":"1,000","MazdaCX5GrandTouringLX":"1,000"},' + 
'{"Group":"Relaciones de caja","SubGroup":"5ª","feature":"5ª","Orden":"0","Url":"Relaciones_5","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Relaciones de caja","SubGroup":"5ª","feature":"5ª","Orden":"1","Url":"","Mazda6GTLX":"0,708","MazdaCX5PrimeMT":"0,837","MazdaCX5PrimeAT":"0,708","MazdaCX5Touring4x2":"0,708","MazdaCX5TouringAWD":"0,708","MazdaCX5GranTouring":"0,708","MazdaCX5GrandTouringLX":"0,708"},' + 
'{"Group":"Relaciones de caja","SubGroup":"6ª","feature":"6ª","Orden":"0","Url":"Relaciones_6","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Relaciones de caja","SubGroup":"6ª","feature":"6ª","Orden":"1","Url":"","Mazda6GTLX":"0,599","MazdaCX5PrimeMT":"0,680","MazdaCX5PrimeAT":"0,599","MazdaCX5Touring4x2":"0,599","MazdaCX5TouringAWD":"0,599","MazdaCX5GranTouring":"0,599","MazdaCX5GrandTouringLX":"0,599"},' + 
'{"Group":"Relaciones de caja","SubGroup":"Reversa","feature":"Reversa","Orden":"0","Url":"Relaciones_Reversa","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Relaciones de caja","SubGroup":"Reversa","feature":"Reversa","Orden":"1","Url":"","Mazda6GTLX":"3,893","MazdaCX5PrimeMT":"3,724","MazdaCX5PrimeAT":"3,893","MazdaCX5Touring4x2":"3,893","MazdaCX5TouringAWD":"3,893","MazdaCX5GranTouring":"3,893","MazdaCX5GrandTouringLX":"3,893"},' + 
'{"Group":"Relaciones de caja","SubGroup":"Relación final de eje","feature":"Relación final de eje","Orden":"0","Url":"Relaciones_Eje","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Relaciones de caja","SubGroup":"Relación final de eje","feature":"Relación final de eje","Orden":"1","Url":"","Mazda6GTLX":"4,056","MazdaCX5PrimeMT":"4,705","MazdaCX5PrimeAT":"4,624","MazdaCX5Touring4x2":"4,624","MazdaCX5TouringAWD":"4,624","MazdaCX5GranTouring":"4,624","MazdaCX5GrandTouringLX":"4,624"},' + 
'{"Group":"Relaciones de caja","SubGroup":"Convertidor de torque","feature":"Convertidor de torque","Orden":"0","Url":"Relaciones_Convertidor","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Relaciones de caja","SubGroup":"Convertidor de torque","feature":"Convertidor de torque","Orden":"1","Url":"","Mazda6GTLX":"1,74","MazdaCX5PrimeMT":"-","MazdaCX5PrimeAT":"1,82","MazdaCX5Touring4x2":"1,82","MazdaCX5TouringAWD":"1,82","MazdaCX5GranTouring":"1,74","MazdaCX5GrandTouringLX":"1,74"},' + 
'{"Group":"Relaciones de caja","SubGroup":"Selección modo de conducción","feature":"Selección modo de conducción","Orden":"0","Url":"Relaciones_Modo","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Relaciones de caja","SubGroup":"Selección modo de conducción","feature":"Selección modo de conducción","Orden":"1","Url":"","Mazda6GTLX":"Sport","MazdaCX5PrimeMT":"-","MazdaCX5PrimeAT":"Sport","MazdaCX5Touring4x2":"Sport","MazdaCX5TouringAWD":"Sport","MazdaCX5GranTouring":"Sport","MazdaCX5GrandTouringLX":"Sport"},' + 
'{"Group":"SKYACTIV-CHASSIS : Suspensión","SubGroup":"Delantera","feature":"Delantera","Orden":"0","Url":"Suspension_Delantera","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-CHASSIS : Suspensión","SubGroup":"Delantera","feature":"Delantera","Orden":"1","Url":"","Mazda6GTLX":"Independiente tipo McPherson/Barra estabilizadora","MazdaCX5PrimeMT":"Independiente tipo McPherson / Barra estabilizadora","MazdaCX5PrimeAT":"Independiente tipo McPherson / Barra estabilizadora","MazdaCX5Touring4x2":"Independiente tipo McPherson / Barra estabilizadora","MazdaCX5TouringAWD":"Independiente tipo McPherson / Barra estabilizadora","MazdaCX5GranTouring":"Independiente tipo McPherson / Barra estabilizadora","MazdaCX5GrandTouringLX":"Independiente tipo McPherson / Barra estabilizadora"},' + 
'{"Group":"SKYACTIV-CHASSIS : Suspensión","SubGroup":"Trasera","feature":"Trasera","Orden":"0","Url":"Suspension_Trasera","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"SKYACTIV-CHASSIS : Suspensión","SubGroup":"Trasera","feature":"Trasera","Orden":"1","Url":"","Mazda6GTLX":"Independiente multibrazos tipo \\"E\\" /Barra estabilizadora","MazdaCX5PrimeMT":"Independiente / Multibrazos tipo \\"E\\" / Barra estabilizadora","MazdaCX5PrimeAT":"Independiente / Multibrazos tipo \\"E\\" / Barra estabilizadora","MazdaCX5Touring4x2":"Independiente / Multibrazos tipo \\"E\\" / Barra estabilizadora","MazdaCX5TouringAWD":"Independiente / Multibrazos tipo \\"E\\" / Barra estabilizadora","MazdaCX5GranTouring":"Independiente / Multibrazos tipo \\"E\\" / Barra estabilizadora","MazdaCX5GrandTouringLX":"Independiente / Multibrazos tipo \\"E\\" / Barra estabilizadora"},' + 
'{"Group":"Ruedas","SubGroup":"Rin","feature":"Rin","Orden":"0","Url":"Ruedas_Rin","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Ruedas","SubGroup":"Rin","feature":"Rin","Orden":"1","Url":"","Mazda6GTLX":"19\\" X 7,5 J Aluminio","MazdaCX5PrimeMT":"17\\" x 7J Aluminio","MazdaCX5PrimeAT":"17\\" x 7J Aluminio","MazdaCX5Touring4x2":"17\\" x 7J Aluminio","MazdaCX5TouringAWD":"17\\" x 7J Aluminio","MazdaCX5GranTouring":"17\\" x 7J Aluminio","MazdaCX5GrandTouringLX":"19\\" x 7J Aluminio"},' + 
'{"Group":"Ruedas","SubGroup":"Llantas","feature":"Llantas","Orden":"0","Url":"Ruedas_Llantas","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Ruedas","SubGroup":"Llantas","feature":"Llantas","Orden":"1","Url":"","Mazda6GTLX":"225/45R19 92W","MazdaCX5PrimeMT":"225/65 R17 102V","MazdaCX5PrimeAT":"225/65 R17 102V","MazdaCX5Touring4x2":"225/65 R17 102V","MazdaCX5TouringAWD":"225/65 R17 102V","MazdaCX5GranTouring":"225/65 R17 102V","MazdaCX5GrandTouringLX":"225/55 R19 99V"},' + 
'{"Group":"Ruedas","SubGroup":"Llanta de repuesto","feature":"Llanta de repuesto","Orden":"0","Url":"Ruedas_Repuesto","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Ruedas","SubGroup":"Llanta de repuesto","feature":"Llanta de repuesto","Orden":"1","Url":"","Mazda6GTLX":"Temporal 185/55R16, Rin 16 X 5J","MazdaCX5PrimeMT":"Temporal 185/80 R17","MazdaCX5PrimeAT":"Temporal 185/80 R17","MazdaCX5Touring4x2":"Temporal 185/80 R17","MazdaCX5TouringAWD":"Temporal 185/80 R17","MazdaCX5GranTouring":"Temporal 185/80 R17","MazdaCX5GrandTouringLX":"Temporal 185/80 R17"},' + 
'{"Group":"Dirección","SubGroup":"Tipo","feature":"Tipo","Orden":"0","Url":"Direccion_Tipo","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dirección","SubGroup":"Tipo","feature":"Tipo","Orden":"1","Url":"","Mazda6GTLX":"Asistida eléctricamente (EPS), regulación según vel. vehículo y r.p.m. de motor","MazdaCX5PrimeMT":"Asistida eléctricamente (EPS), regulación según vel. vehículo y r.p.m de motor","MazdaCX5PrimeAT":"Asistida eléctricamente (EPS), regulación según vel. vehículo y r.p.m de motor","MazdaCX5Touring4x2":"Asistida eléctricamente (EPS), regulación según vel. vehículo y r.p.m de motor","MazdaCX5TouringAWD":"Asistida eléctricamente (EPS), regulación según vel. vehículo y r.p.m de motor","MazdaCX5GranTouring":"Asistida eléctricamente (EPS), regulación según vel. vehículo y r.p.m de motor","MazdaCX5GrandTouringLX":"Asistida eléctricamente (EPS), regulación según vel. vehículo y r.p.m de motor"},' + 
'{"Group":"Dirección","SubGroup":"Radio de giro entre andenes (m)","feature":"Radio de giro entre andenes (m)","Orden":"0","Url":"Direccion_Radio","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dirección","SubGroup":"Radio de giro entre andenes (m)","feature":"Radio de giro entre andenes (m)","Orden":"1","Url":"","Mazda6GTLX":"5,6","MazdaCX5PrimeMT":"5,6","MazdaCX5PrimeAT":"5,6","MazdaCX5Touring4x2":"5,6","MazdaCX5TouringAWD":"5,6","MazdaCX5GranTouring":"5,6","MazdaCX5GrandTouringLX":"5,6"},' + 
'{"Group":"Dirección","SubGroup":"Volante con cuero","feature":"Volante con cuero","Orden":"0","Url":"Direccion_Volante","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dirección","SubGroup":"Volante con cuero","feature":"Volante con cuero","Orden":"1","Url":"","Mazda6GTLX":"Sí","MazdaCX5PrimeMT":"-","MazdaCX5PrimeAT":"-","MazdaCX5Touring4x2":"Sí","MazdaCX5TouringAWD":"Sí","MazdaCX5GranTouring":"Sí","MazdaCX5GrandTouringLX":"Sí"},' + 
'{"Group":"Dirección","SubGroup":"Control de cambios en el volante","feature":"Control de cambios en el volante","Orden":"0","Url":"Direccion_Control","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dirección","SubGroup":"Control de cambios en el volante","feature":"Control de cambios en el volante","Orden":"1","Url":"","Mazda6GTLX":"Sí","MazdaCX5PrimeMT":"-","MazdaCX5PrimeAT":"-","MazdaCX5Touring4x2":"-","MazdaCX5TouringAWD":"-","MazdaCX5GranTouring":"-","MazdaCX5GrandTouringLX":"-"},' + 
'{"Group":"Sistema de Frenos","SubGroup":"Tipo","feature":"Tipo","Orden":"0","Url":"Frenos_Tipo","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Sistema de Frenos","SubGroup":"Tipo","feature":"Tipo","Orden":"1","Url":"","Mazda6GTLX":"ABS/EBD/BA","MazdaCX5PrimeMT":"ABS / EBD / BA","MazdaCX5PrimeAT":"ABS / EBD / BA","MazdaCX5Touring4x2":"ABS / EBD / BA","MazdaCX5TouringAWD":"ABS / EBD / BA","MazdaCX5GranTouring":"ABS / EBD / BA","MazdaCX5GrandTouringLX":"ABS / EBD / BA"},' + 
'{"Group":"Sistema de Frenos","SubGroup":"Delanteros","feature":"Delanteros","Orden":"0","Url":"Frenos_Delanteros","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Sistema de Frenos","SubGroup":"Delanteros","feature":"Delanteros","Orden":"1","Url":"","Mazda6GTLX":"Disco ventilado","MazdaCX5PrimeMT":"Disco ventilado","MazdaCX5PrimeAT":"Disco ventilado","MazdaCX5Touring4x2":"Disco ventilado","MazdaCX5TouringAWD":"Disco ventilado","MazdaCX5GranTouring":"Disco ventilado","MazdaCX5GrandTouringLX":"Disco ventilado"},' + 
'{"Group":"Sistema de Frenos","SubGroup":"Traseros","feature":"Traseros","Orden":"0","Url":"Frenos_Traseros","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Sistema de Frenos","SubGroup":"Traseros","feature":"Traseros","Orden":"1","Url":"","Mazda6GTLX":"Disco sólido","MazdaCX5PrimeMT":"Disco sólido","MazdaCX5PrimeAT":"Disco sólido","MazdaCX5Touring4x2":"Disco sólido","MazdaCX5TouringAWD":"Disco sólido","MazdaCX5GranTouring":"Disco sólido","MazdaCX5GrandTouringLX":"Disco sólido"},' + 
'{"Group":"Sistema de Frenos","SubGroup":"Parqueo","feature":"Parqueo","Orden":"0","Url":"Frenos_Parqueo","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Sistema de Frenos","SubGroup":"Parqueo","feature":"Parqueo","Orden":"1","Url":"","Mazda6GTLX":"Accionamiento eléctrico, liberación automática","MazdaCX5PrimeMT":"Accionamiento eléctrico","MazdaCX5PrimeAT":"Accionamiento eléctrico","MazdaCX5Touring4x2":"Accionamiento eléctrico","MazdaCX5TouringAWD":"Accionamiento eléctrico","MazdaCX5GranTouring":"Accionamiento eléctrico","MazdaCX5GrandTouringLX":"Accionamiento eléctrico"},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Longitud total (mm)","feature":"Longitud total (mm)","Orden":"0","Url":"Dimensiones_Longitud","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Longitud total (mm)","feature":"Longitud total (mm)","Orden":"1","Url":"","Mazda6GTLX":"4.870","MazdaCX5PrimeMT":"4.540","MazdaCX5PrimeAT":"4.540","MazdaCX5Touring4x2":"4.540","MazdaCX5TouringAWD":"4.540","MazdaCX5GranTouring":"4.540","MazdaCX5GrandTouringLX":"4.540"},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Ancho total (mm)","feature":"Ancho total (mm)","Orden":"0","Url":"Dimensiones_Ancho","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Ancho total (mm)","feature":"Ancho total (mm)","Orden":"1","Url":"","Mazda6GTLX":"1.840","MazdaCX5PrimeMT":"1.840","MazdaCX5PrimeAT":"1.840","MazdaCX5Touring4x2":"1.840","MazdaCX5TouringAWD":"1.840","MazdaCX5GranTouring":"1.840","MazdaCX5GrandTouringLX":"1.840"},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Altura total (mm)","feature":"Altura total (mm)","Orden":"0","Url":"Dimensiones_Altura","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Altura total (mm)","feature":"Altura total (mm)","Orden":"1","Url":"","Mazda6GTLX":"1.450","MazdaCX5PrimeMT":"1.670","MazdaCX5PrimeAT":"1.670","MazdaCX5Touring4x2":"1.670","MazdaCX5TouringAWD":"1.670","MazdaCX5GranTouring":"1.670","MazdaCX5GrandTouringLX":"1.670"},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Distancia entre ejes (mm)","feature":"Distancia entre ejes (mm)","Orden":"0","Url":"Dimensiones_Distancia","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Distancia entre ejes (mm)","feature":"Distancia entre ejes (mm)","Orden":"1","Url":"","Mazda6GTLX":"2.830","MazdaCX5PrimeMT":"2.700","MazdaCX5PrimeAT":"2.700","MazdaCX5Touring4x2":"2.700","MazdaCX5TouringAWD":"2.700","MazdaCX5GranTouring":"2.700","MazdaCX5GrandTouringLX":"2.700"},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Trocha delantera (mm)","feature":"Trocha delantera (mm)","Orden":"0","Url":"Dimensiones_Delantera","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Trocha delantera (mm)","feature":"Trocha delantera (mm)","Orden":"1","Url":"","Mazda6GTLX":"1.595","MazdaCX5PrimeMT":"1.585","MazdaCX5PrimeAT":"1.585","MazdaCX5Touring4x2":"1.585","MazdaCX5TouringAWD":"1.585","MazdaCX5GranTouring":"1.585","MazdaCX5GrandTouringLX":"1.585"},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Trocha trasera (mm)","feature":"Trocha trasera (mm)","Orden":"0","Url":"Dimensiones_Trasera","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Trocha trasera (mm)","feature":"Trocha trasera (mm)","Orden":"1","Url":"","Mazda6GTLX":"1.585","MazdaCX5PrimeMT":"1.590","MazdaCX5PrimeAT":"1.590","MazdaCX5Touring4x2":"1.590","MazdaCX5TouringAWD":"1.590","MazdaCX5GranTouring":"1.590","MazdaCX5GrandTouringLX":"1.590"},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Voladizo delantero (mm)","feature":"Voladizo delantero (mm)","Orden":"0","Url":"Dimensiones_Delantero","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Voladizo delantero (mm)","feature":"Voladizo delantero (mm)","Orden":"1","Url":"","Mazda6GTLX":"-","MazdaCX5PrimeMT":"935","MazdaCX5PrimeAT":"935","MazdaCX5Touring4x2":"935","MazdaCX5TouringAWD":"935","MazdaCX5GranTouring":"935","MazdaCX5GrandTouringLX":"935"},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Voladizo trasero (mm)","feature":"Voladizo trasero (mm)","Orden":"0","Url":"Dimensiones_Trasero","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Voladizo trasero (mm)","feature":"Voladizo trasero (mm)","Orden":"1","Url":"","Mazda6GTLX":"-","MazdaCX5PrimeMT":"905","MazdaCX5PrimeAT":"905","MazdaCX5Touring4x2":"905","MazdaCX5TouringAWD":"905","MazdaCX5GranTouring":"905","MazdaCX5GrandTouringLX":"905"},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Capacidad del baúl (L)","feature":"Capacidad del baúl (L)","Orden":"0","Url":"Dimensiones_Capacidad","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Capacidad del baúl (L)","feature":"Capacidad del baúl (L)","Orden":"1","Url":"","Mazda6GTLX":"429","MazdaCX5PrimeMT":"403","MazdaCX5PrimeAT":"403","MazdaCX5Touring4x2":"403","MazdaCX5TouringAWD":"403","MazdaCX5GranTouring":"403","MazdaCX5GrandTouringLX":"403"},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Peso vacío (kg)","feature":"Peso vacío (kg)","Orden":"0","Url":"Dimensiones_Peso","Mazda6GTLX":"","MazdaCX5PrimeMT":"","MazdaCX5PrimeAT":"","MazdaCX5Touring4x2":"","MazdaCX5TouringAWD":"","MazdaCX5GranTouring":"","MazdaCX5GrandTouringLX":""},' + 
'{"Group":"Dimensiones y pesos","SubGroup":"Peso vacío (kg)","feature":"Peso vacío (kg)","Orden":"1","Url":"","Mazda6GTLX":"1456","MazdaCX5PrimeMT":"1.430","MazdaCX5PrimeAT":"1.455","MazdaCX5Touring4x2":"1.455","MazdaCX5TouringAWD":"1.505","MazdaCX5GranTouring":"1.595","MazdaCX5GrandTouringLX":"1600"}' + 
']}';
